const $ = s => document.querySelector(s);
const currency = n => `₦${Number(n || 0).toLocaleString('en-NG',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const stored = () => JSON.parse(localStorage.getItem('otechInvoices') || '[]');
const saveStored = v => localStorage.setItem('otechInvoices', JSON.stringify(v));
let signatureDrawn = false;

function nextNumber(){const n=Number(localStorage.getItem('otechInvoiceSequence')||0)+1;localStorage.setItem('otechInvoiceSequence',n);return `OTECH-${new Date().getFullYear()}-${String(n).padStart(4,'0')}`}
function addRow(data={}){const row=$('#row-template').content.firstElementChild.cloneNode(true);row.querySelector('.description').value=data.description||'';row.querySelector('.quantity').value=data.quantity||1;row.querySelector('.price').value=data.price||'';row.querySelectorAll('input').forEach(i=>i.addEventListener('input',calculate));row.querySelector('.remove-row').addEventListener('click',()=>{row.remove();calculate()});$('#items').append(row);calculate()}
function calculate(){let total=0;document.querySelectorAll('#items tr').forEach(row=>{const q=Number(row.querySelector('.quantity').value)||0,p=Number(row.querySelector('.price').value)||0,a=q*p;row.querySelector('.amount').textContent=currency(a);total+=a});$('#subtotal').textContent=currency(total);$('#total').textContent=currency(total);return total}
function resetInvoice(){ $('#customer-name').value='';$('#customer-contact').value='';$('#invoice-number').value=nextNumber();$('#invoice-date').value=new Date().toISOString().slice(0,10);$('#notes').value='';$('#signature-required').checked=false;$('#signature-section').classList.add('hidden');$('#items').innerHTML='';addRow();clearSignature() }
function readInvoice(){return {number:$('#invoice-number').value,customer:$('#customer-name').value||'Walk-in customer',contact:$('#customer-contact').value,date:$('#invoice-date').value,notes:$('#notes').value,total:calculate(),items:[...document.querySelectorAll('#items tr')].map(r=>({description:r.querySelector('.description').value,quantity:r.querySelector('.quantity').value,price:r.querySelector('.price').value})),signed:signatureDrawn,created:new Date().toISOString()}}
function saveInvoice(){const invoice=readInvoice();if(!invoice.items.some(i=>i.description||i.price)){alert('Add at least one good or service before saving.');return}const all=stored();const index=all.findIndex(x=>x.number===invoice.number);if(index>-1)all[index]=invoice;else all.unshift(invoice);saveStored(all);renderAll();alert('Invoice saved on this device.');}
function renderAll(){const all=stored(), total=all.reduce((a,x)=>a+Number(x.total||0),0);$('#stat-count').textContent=all.length;$('#stat-total').textContent=currency(total);$('#stat-latest').textContent=all[0]?.number||'—';const markup=all.slice(0,5).map(rowHTML).join('');$('#recent-list').innerHTML=markup||'No invoices saved yet.';$('#recent-list').className='invoice-list '+(markup?'':'empty');$('#saved-list').innerHTML=all.length?all.map(rowHTML).join(''):'<div class="empty-state">No saved invoices yet. Create your first invoice to begin.</div>';document.querySelectorAll('.delete-invoice').forEach(b=>b.addEventListener('click',()=>{if(confirm('Delete this saved invoice?')){saveStored(stored().filter(x=>x.number!==b.dataset.number));renderAll()}}))}
function rowHTML(x){return `<div class="saved-row"><strong>${x.number}</strong><span>${x.customer}</span><span>${x.date||'No date'}</span><strong>${currency(x.total)}</strong><button class="text-button delete-invoice" data-number="${x.number}">Delete</button></div>`}
function show(view){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===view));document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view));$('#page-title').textContent=view==='dashboard'?'Dashboard':view==='invoice'?'New invoice':'Saved invoices';if(view==='invoice'&&!$('#invoice-number').value)resetInvoice();window.scrollTo(0,0)}
function clearSignature(){const c=$('#signature-pad'),ctx=c.getContext('2d');ctx.clearRect(0,0,c.width,c.height);signatureDrawn=false}
function setupSignature(){const c=$('#signature-pad'),ctx=c.getContext('2d');function resize(){const data=signatureDrawn?c.toDataURL():null;c.width=c.offsetWidth*devicePixelRatio;c.height=c.offsetHeight*devicePixelRatio;ctx.scale(devicePixelRatio,devicePixelRatio);if(data){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,c.offsetWidth,c.offsetHeight);img.src=data}}resize();new ResizeObserver(resize).observe(c);let drawing=false,last;const point=e=>{const r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:p.clientX-r.left,y:p.clientY-r.top}};const start=e=>{drawing=true;last=point(e);e.preventDefault()};const move=e=>{if(!drawing)return;const now=point(e);ctx.strokeStyle='#152b45';ctx.lineWidth=2;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(now.x,now.y);ctx.stroke();last=now;signatureDrawn=true;e.preventDefault()};c.addEventListener('pointerdown',start);c.addEventListener('pointermove',move);window.addEventListener('pointerup',()=>drawing=false);$('#clear-signature').addEventListener('click',clearSignature)}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.go)));document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));$('#new-invoice').addEventListener('click',()=>{resetInvoice();show('invoice')});$('#welcome-new').addEventListener('click',()=>{resetInvoice();show('invoice')});$('#add-row').addEventListener('click',()=>addRow());$('#save-draft').addEventListener('click',saveInvoice);$('#print-invoice').addEventListener('click',()=>window.print());$('#signature-required').addEventListener('change',e=>$('#signature-section').classList.toggle('hidden',!e.target.checked));
setupSignature();resetInvoice();renderAll();
